// app/layout.tsx (Global Layout)
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@components/navbar/navbar"; // Global Navbar
import Footer from "@components/footer/footer"; // Global Footer
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar /> {/* Global Navbar */}
        {children} {/* Main content */}
        <Footer /> {/* Global Footer */}
      </body>
    </html>
  );
}
